import Navbar from '@/components/Navbar';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from "@/components/ui/toaster"
import {Provider, QueryProvider} from '@/components/Provider';
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider>
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
            <QueryProvider>
              <main style={{minHeight: "100vh"}}>
                <Navbar />
                <div className='container pt-12'>
                  {children}
                </div>
              </main>
            </QueryProvider>
          </ThemeProvider>
        </Provider>
        <Toaster />
      </body>
    </html>
  );
}